const strings: Record<string, any> = {
	en: {
		back: "Back",
		save: "Save",
		add: "Add a Goal",
		title: "Title",
		description: "Description",
		prompts: [
			"Go fishing in the Northwest Territories",
			"Climb on a glacier in Alaska",
			"Go on a safari in Africa",
			"Become a certified scuba diver",
			"Snorkel in Hawaii",
			"Learn to sail",
			"Skydive",
			"Ride in a hot air balloon",
			"Go on a river-rafting trip",
			"Go kayaking",
			"Fly in a glider",
			"Dive in a submarine",
			"Learn to windsurf",
			"Learn to ski",
			"Swim with the dolphins",
			"Go to the Super Bowl",
			"Go to the Olympics",
			"Run a 10k race",
			"Run 14 miles in less than 3 hours",
			"Meet a U.S. president while he/she is still in office",
			"Own my own pool table",
			"Publish a book",
			"Learn to speak Spanish fluently",
			"Learn to paint with oils",
			"Publish a poem",
			"Master 5 magic tricks",
			"Learn to sing and play 10 popular songs on the guitar",
			"Bench press 200 pounds",
			"Run a mile under 6 minutes",
			"Do a fire-walk",
			"Visit Buenos Aires, Argentina",
			"Visit Japan",
			"Go to Dubai"
		]
	},
	cs: {
		back: "Zpět",
		save: "Uložit",
		add: "Přidat cíl",
		title: "Název",
		description: "Popis",
		prompts: [
			"vytvořit vlastní malovaný kalendář",
			"naučit se poskládat 10 různých origami (zpaměti)",
			"vytvořit 1000 origami jeřábů (a pak si přát přání)",
			"sdílet v ulicích vlastní zentangle na omalování",
			"naučit se šít a ušít si sukni",
			"vydlabat si vlastní sadu dřevěných misek",
			"naučit se kreslit fixama",
			"projít si kurz olejomalby a vytvořit první obraz",
			"pravidelně si vytvářet a vést bullet journal",
			"z přečtených knih vytvářet výpisky (a publikovat je)",
			"myšlenkové mapy z přečtených knih",
			"Nechat 11× vzkaz v knize z knihovny",
			"umět psát všemi 10 (21 kláves)",
			"naučit se žonglovat (alespoň se 3 míčky)",
			"naučit se pískat na prsty",
			"udělat si řidičák B",
			"naučit se anglicky",
			"absolvovat pobyt ve tmě",
			"absolvovat netradiční kurz vaření",
			"jít na degustaci vín nebo kávy",
			"naučit se míchat koktejly",
			"naučit se základy programování",
			"naučit se složit rubikovu kostku",
			"oprášit hru na klavír a naučit se 10 nových skladeb (třeba z filmů)",
			"naučit se hrát na zobcovou flétnu",
			"zkusit držet půst",
			"zkusit meditaci",
			"založit si snový deník a zapisovat sny",
			"radikálně minimalizovat počet svých věcí",
			"vytvořit si fotoalba z minulých let a vytisknout fotoknihu",
			"napsat si 10 pohledů z 10 různých míst",
			"užít si celý den ve 13 městech ČR",
			"přijít na nádraží, koupit lístek na první vlak a udělat neplánovaný výlet",
			"navštívit a projít si 7 hradů v ČR",
			"projít a zdokumentovat 10 naučných stezek ČR",
			"navštívit 3 různé ZOO v ČR",
			"vypravit se a nalézt 10 kešek",
			"jít na pražské trhy o svátcích",
			"projet se šlapadlem po Vltavě",
			"proletět se balónem",
			"navštívit 5 neznámých čajoven v Praze",
			"navštívit 10 nových restaurací v Praze",
			"postavit sněhuláka většího než jsem já",
			"zhlédnout film v letním kině",
			"jít na 4 divadelní představení",
			"navštívit 8 výstav",
			"být na jeden den YES (wo)MAN",
			"být jeden den bez PC a mobilu"
		]
	}
};

export default strings;
